// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import LenisProvider from "./provider/LenisProvider";
// import "./globals.css";
// // import Header from "@/components/Header";
// import Cursor from "@/components/Cursor";
// import Footer from "@/components/footer";

// const toyotaFont = localFont({
//   src: [
//     {
//       path: "../fonts/toyotatype-book-webfont.woff2",
//       weight: "300",
//       style: "normal",
//     },
//     {
//       path: "../fonts/toyotatype-regular-webfont.woff2",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../fonts/toyotatype-semibold-webfont.woff2",
//       weight: "600",
//       style: "normal",
//     },
//     {
//       path: "../fonts/toyotatype-black.woff2", // convert .ttf → .woff2
//       weight: "900",
//       style: "normal",
//     },
//   ],
//   variable: "--toyota-font",
// });

// const playlistFont = localFont({
//   src: [
//     {
//       path: "../fonts/playlist.woff2",
//       weight: "400",
//       style: "normal",
//     },
//   ],
//   variable: "--playlist-font",
// });

// export const metadata: Metadata = {
//   title: "Toyota Indus",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${toyotaFont.variable} ${playlistFont.variable} antialiased`}
//       >
//         <LenisProvider>
//           {/* <Header /> */}
//           <main className="bg-[#FFFEF9] z-10">
//             <Cursor />
//             {children}
//           </main>
//           <Footer />
//         </LenisProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import localFont from "next/font/local";
import LenisProvider from "./provider/LenisProvider";
import "./globals.css";
import Cursor from "@/components/Cursor";
import Footer from "@/components/footer";
import Header from "@/components/Header";
import FooterParallaxShell from "@/components/FooterParallaxShell";

const toyotaFont = localFont({
  src: [
    {
      path: "../fonts/toyotatype-book-webfont.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/toyotatype-regular-webfont.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/toyotatype-semibold-webfont.woff2",
      weight: "600",
      style: "normal",
    },
    { path: "../fonts/toyotatype-black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--toyota-font",
});

const playlistFont = localFont({
  src: [{ path: "../fonts/playlist.woff2", weight: "400", style: "normal" }],
  variable: "--playlist-font",
});

export const metadata: Metadata = {
  title: "Toyota Indus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${toyotaFont.variable} ${playlistFont.variable} antialiased`}
      >
        <LenisProvider>
          <FooterParallaxShell footer={<Footer />}>
            <Header />
            <main className="relative z-10 bg-[#FFFEF9]">
              <Cursor />
              {children}
            </main>
          </FooterParallaxShell>
        </LenisProvider>
      </body>
    </html>
  );
}
